sudo: required
services:
  - docker
language: python

python:
  - '2.7'

addons:
  postgresql: '9.3'

cache:
  directories:
    - $HOME/.cache/pip

install:
  - docker-compose build
  - docker-compose up -d

before_script:
  - find . -name '*.pyc' -delete
  - coverage erase

script:
  - docker-compose run django python manage.py makemigrations --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)
  - docker-compose run django coverage run manage.py test thyng
  - docker-compose run django coverage report -m --fail-under 80
  - docker-compose run django flake8 . --exclude=ve,settings.py,migrations

notifications:
  email: false
  slack: socialplanningdotorg:FEsWAxu2sKXNQKqoWngbx7pq
    


