django:
  restart: always
  build: ./django
  expose:
    - "8000"
  volumes:
    - /code
    - /code/static
  links:
      - postgres:postgres
  env_file: .env
  command: python manage.py runserver 0.0.0.0:8000

deliverance:
  restart: always
  build: ./deliverance
  expose:
    - "8002"
  volumes:
    - /code
  links:
    - django:django
    - trac:trac
  env_file: .env
  command: python wsgi.py 8002

trac:
  restart: always
  build: ./trac
  expose:
    - "8001"
  volumes:
    - /code
    - tracsites:/srv/my-sites
  links:
      - postgres:postgres
  env_file: .env
  command: tracd -p 8001 -e /srv/my-sites

postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - django
  links:
    - deliverance:deliverance
