# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thyng', '0003_auto_20160522_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFeaturelet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=25)),
                ('proxy', models.CharField(max_length=25)),
                ('instance', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thyng.Project')),
            ],
        ),
    ]
